AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Create function to test logging
Resources:
  function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: functions/.
      Description: Call Function 1
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: logging-lib
      Description: Loggings dependencies for Serverless app
      ContentUri: aws-logging-layer/.
      CompatibleRuntimes:
        - nodejs14.x      
